language: c

env:
  - EnableNuGetPackageRestore=true

before_install:
  # Make sure mono is installed,
  # pipe stdout to dev/null because qq is still too chatty
  # Adding the mono-experimental build, because Ubuntu 12.04 uses mono 2.10,
  # which doesn't include Microsoft.Build.dll, which is needed
  # for NuGet.exe to function properly.
  #
  # Shame on us for appending to sources.list, but it's simple, fast and used
  # only for TravisCI
  - echo " deb http://debian.meebey.net/experimental/mono /" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-complete mono-gmcs > /dev/null
  # update root certs for nuget
  - mozroots --import --sync
  - chmod a+x .ci/build.sh

script:
  - .ci/build.sh
